# Languages
#   Create a `[X]` block for each language you want, where X is the language ID.
#   Refer to https://sourcethemes.com/academic/docs/language/

# Configure the English version of the site.
[en]
  languageCode = "en-us"
  title = "Desirrê Petters-Vandresen"
  contentDir = "content/en"  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.

# Uncomment the lines below to configure your website in a second language.
[pt]
  languageCode = "pt"
  contentDir = "content/pt"
  title = "Desirrê Petters-Vandresen"
  [pt.params]
    description = "Site description in Chinese..."
  [[pt.menu.main]]
    name = "Sobre mim"
    url = "#about"
    weight = 1
  [[pt.menu.main]]
    name = "Posts"
    url = "#posts"
    weight = 20
  [[pt.menu.main]]
    name = "Projetos"
    url = "#projects"
    identifier = "projects"
    weight = 30
  [[pt.menu.main]]
  name = "Comparação de genomas de espécies de Phyllosticta associadas a Citros"
  url = "project/phyllosticta-genomes"
  parent = "projects"
  weight = 1
  [[pt.menu.main]]
  name = "Análises funcionais de espécies de Phyllosticta associadas a Citros"
  url = "project/phyllosticta-functional"
  parent = "projects"
  weight = 2